import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import 'react-icons/fa6';

import './globals.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Store Application | Devendra Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
